version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "monthly"
    labels:
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Maintain dependencies for Golang
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "deps"
      include: "scope"
