---
# --- Component Versions ---
k8s_version:          "1.30.0"
containerd_version:   "2.1.2"
runc_version:         "1.2.6"
cni_version:          "1.6.2"

# --- System Configuration ---
arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
cluster_cidr:         "10.216.0.0/16"   # 216 = 6^3 (Cube)
service_cidr:         "10.216.224.0/24" # 224 = 4^2+8^2+12^2 (sum of 3 squares)
pod_network_cidr:     "10.144.0.0/16"   # fibonnacci number
clusterDNS:           "10.216.224.53"   # 53 = DNS port

# --- Paths (standard K8s paths) ---
cni_net_dir:          "/etc/cni/net.d"
container_config_dir: "/etc/containerd"
config_path:          "/etc/kubernetes"
pki_path:             "/etc/kubernetes/pki"
cni_path:             "/opt/cni/bin"
bin_path:             "/usr/local/bin"
etcd_data_path:       "/var/lib/etcd"
kubelet_data_path:    "/var/lib/kubelet"
kubernetes_log_path:  "/var/log/kubernetes"
