---
- name: "Install K8s on Fedora Core OS"
  hosts: [localhost]
  connection: local
  become: true
  vars:
    # --- Component Versions ---
    k8s_version: "1.30.0"
    containerd_version: "2.1.2"
    runc_version: "1.2.6"
    cni_version: "1.6.2"
    etcd_version: "v3.5.14"

    # --- System Configuration ---
    arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
    pod_network_cidr: "10.244.0.0/16"
    service_cidr: "10.96.0.0/12"

    # --- Paths ---
    k8s_pki_path: "/etc/kubernetes/pki"
    k8s_config_path: "/etc/kubernetes"
    kubelet_dir: "/var/lib/kubelet"
    bin_path: "/usr/local/bin"
    wip_dir: "/srv/k8s"
  tasks:
    - name: Hello world
      debug:
        msg: "Hello world"

